# The regex used is a bit different from original documenation:
# https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#loading-data-from-other-files
# Original documentation implies that the __init__.py only has one line with __version__
---
{% set version_match = load_file_regex(load_file="brightway25/__init__.py", 
regex_pattern='(?:.*)__version__ = "(.+)"') %}

{% set version = version_match[1] %}


package:
        name: brightway25
        version: {{ version }}

source:
        path: ../

requirements:
        build:
                - python
                - setuptools
        run:
                - bw2calc >= 2.0.1
                - bw2data >= 4.4.2
                - bw2io >= 0.9.6
                - bw2parameters >= 1.1.0
                - bw_migrations >= 0.2
                - bw_processing >= 1.0
                - bw_simapro_csv >= 0.4
                - ecoinvent_interface >= 3.1
                - matrix_utils >= 0.6
                - mrio_common_metadata >= 0.2.1
                - multifunctional >= 1.0
                - numpy < 2
                - python >=3.9
                - randonneur >= 0.6.1
                - randonneur_data >= 0.5.5
                - stats_arrays >= 0.7

about:
        home: https://github.com/brightway-lca/brightway25
        license: BSD-3-Clause
        license_file: LICENSE

build:
        noarch: python
        script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv
