---
name: Build and deploy conda package

on:
  push:
    branches: [main, develop]
    tags: '*'
    paths-ignore:
      # Don't re-build if we only change README.md Or CHANGES.md
      - '**.md'
jobs:
  conda-pkg-build:
    name: build
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.12
          auto-activate-base: true
      - name: Publish distribution 📦 to conda channels
        if: startsWith(github.ref, 'refs/tags')
        run: |
          conda info
          conda config --set auto_update_conda False
          conda install -y -q conda-build anaconda-client
          anaconda login --username ${{ secrets.ANACONDA_USER }} --password "${{ secrets.ANACONDA_PASSWORD }}"
          conda config --set anaconda_upload yes
          conda build -c conda-forge conda.recipe .
